apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-jenkins
  namespace: argocd
spec:
  destination:
    namespace: jenkins
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: .
    repoURL: https://github.com/nchandra10/argocd-jenkins-app.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
